name: Terraform plan and Apply
on:
  workflow_dispatch:
  #push:
   # branches:
    # - main
  
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: read
  issues: write

concurrency: cloudsentrics # This will ensure only a single workflow is run at a time


jobs:
  kics:
    name: Run KICS Code Analysis
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{github.event.pull_request.head.ref}}

    - name: Run KICS Scan
      uses: checkmarx/kics-github-action@v2.0.0
      with:
        path: ./infrastructure/region/iam_group
        token: ${{ secrets.GITHUB_TOKEN }}
        output_path: myResults/
        ignore_on_exit: results
        enable_comments: true

    - name: Display KICS results
      run: |
        cat myResults/results.json
 
  run_plan_in_prod_environment:
    name: Prod-environment, terraform plan"
    uses: ./.github/workflows/reuseable_plan_actions.yml
    with:
      #ENVIRONMENT_NAME: 'prod'
      TERRAFORM_VERSION: '1.7.4'
      TERRAGRUNT_VERSION: '0.58.0'
      TERRAFORM_WORKING_DIR: ./applied/accounts/prod
      AWS_REGION: 'us-east-1'
    secrets: inherit

  run_apply_in_prod_environment:
    name: prod-environment terraform apply
    needs: [run_plan_in_prod_environment]
    uses: ./.github/workflows/reuseable_apply_actions.yml
    with:
      #ENVIRONMENT_NAME: 'prod'
      TERRAFORM_VERSION: '1.7.2'
      TERRAGRUNT_VERSION: '0.58.0'
      TERRAFORM_WORKING_DIR: ./applied/accounts/prod
      AWS_REGION: 'us-east-1'
    secrets: inherit

  run_plan_dev_environment:
    name: dev-environment terraform plan
    needs: [run_apply_in_prod_environment]
    uses: ./.github/workflows/reuseable_plan_actions.yml
    with:
     #ENVIRONMENT_NAME: 'dev'
     TERRAFORM_VERSION: '1.1.1'
     TERRAGRUNT_VERSION: '0.56.0'
     TERRAFORM_WORKING_DIR: ./applied/accounts/prod
     AWS_REGION: 'us-east-1'
    secrets: inherit
 
  run_apply_in_dev_environment:
    name: dev-environment terraform apply
    needs: [run_plan_dev_environment]
    uses: ./.github/workflows/reuseable_apply_actions.yml
    with:
      #ENVIRONMENT_NAME: 'prod'
      TERRAFORM_VERSION: '1.7.2'
      TERRAGRUNT_VERSION: '0.58.0'
      TERRAFORM_WORKING_DIR: ./applied/accounts/prod
      AWS_REGION: 'us-east-1'
    secrets: inherit


  #run_apply_in_prod_environment:
    #name: terraform init, apply
   # needs: [run_plan_prod_environment]
    #uses: ./.github/workflows/reuseable_apply_actions.yml
    #with:
     # ENVIRONMENT_NAME: 'prod'
     # TERRAFORM_VERSION: '1.7.2'
      #TERRAGRUNT_VERSION: '0.58.0'
      #TERRAFORM_WORKING_DIR: ./applied/accounts/prod
      #AWS_REGION: 'us-east-1'
    #secrets: inherit